spring:
  jpa:
    hibernate:
      ddl-auto: create # test
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service
  main:
    allow-circular-references: true

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.order
    title: order api
    version: 1.0

logging:
  level:
    p6spy: info

grpc:
  server:
    port: 9090
