server:
  port: 8081

grpc:
  client:
    getBookList:
      address: 'static://127.0.0.1:9091'
      negotiationtype: plaintext
    rentalBook:
      address: 'static://127.0.0.1:9091'
      negotiationtype: plaintext
    completeRentalBook:
      address: 'static://127.0.0.1:9091'
      negotiationtype: plaintext

spring:
  jpa:
    hibernate:
      ddl-auto: create # test
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.order
    title: order api
    version: 1.0

logging:
  level:
    p6spy: info


