server:
  port: 8081

grpc:
  commonSettings: &commonSettings
    address: 'static://127.0.0.1:9091'
    negotiationtype: plaintext

  client:
    getBookList: *commonSettings
    rentalBook: *commonSettings
    completeRentalBook: *commonSettings
    rollBackRental: *commonSettings

spring:
  jpa:
    hibernate:
      ddl-auto: update # test
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.order
    title: order api
    version: 1.0

logging:
  level:
    p6spy: info
    org:
      springframework:
        orm:
          jpa: debug

feign:
  client:
    url: paymentServer
